### ISSUE TITLE
UPDATE/DELETE only supports WHERE-clauses on primary keys

### ISSUE THREAD

**Issue by rbraley** [mit-pdos/noria-mysql#11]
Not sure if this belongs here, or noria proper. But it is a blocker for me.

    Nov 25 19:33:09.359 INFO listening on port 3306
    Nov 25 19:35:25.776 WARN Ignoring DROP TABLE query: "DROP TABLE IF EXISTS piwik_test_table, piwik_test_table_temp"
    Nov 25 19:35:25.791 WARN ignoring unsupported query "ALTER TABLE piwik_test_table ADD COLUMN other_value INT DEFAULT 0" and returning empty results
    Nov 25 19:35:25.793 INFO Adding ad-hoc query "SELECT * FROM piwik_test_table" to Noria as q_a0d2afefe8ead9ad
    thread 'conn-0' panicked at 'UPDATE/DELETE only supports WHERE-clauses on primary keys', src/utils.rs:110:17
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
    thread 'conn-1' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "no view or table named \'piwik_test_table_temp\'" }', src/libcore/result.rs:1189:5

**Comment by jonhoo** [comment]
This is a restriction of Noria itself, not just of the shim. The issue here is that a `DELETE` on a non-primary key would be very inefficient, requiring a full scan of all shards of the relevant base table. It may be that the feature is critical enough that that is warranted though.

That said, this is a research prototype, and since this is not a research focus, it is unfortunately unlikely it'll be fixed any time soon. If you want to dig into the code though, I'd be happy to take a look at a PR!

**Comment by rbraley** [comment]
To be honest I am very keen to contribute, and I dove into the code to try. I've never written a SQL query engine, however, so not sure where to learn to create a reasonable PR. I've done a little bit on the frameless library for spark though.

**Comment by jonhoo** [comment]
Ah, excellent! I think the tricks is going to be to first dig into this crate for where that error is raised. See if you can make the shim not reject the `DELETE` and have it instead send it as normal. The delete should make it to `node/special/base.rs` (from memory), which is what handles the deletes. You _may_ need to modify `table.rs` so that it sends a `DELETE` that's not on the primary key to _every_ shard rather than just the "appropriate" shard (since there is no appropriate shard for a non-keyed `DELETE`).
